## Global Variables
@baseurl=https://pam-2026-p9-pastry-be.helgazefanya.site:8080

## Generate Pastry
# @name PostGeneratePastry
POST {{baseurl}}/pastries/generate
Content-Type: application/json

{
  "theme": "Butter Croissant",
  "total": 5
}
###

## Response PostGeneratePastry
{
  "data": [
    "Croissant klasik dengan lapisan mentega yang renyah dan tekstur dalam yang lembut.",
    "Pain au Chocolat dengan dua batang cokelat hitam premium di dalamnya.",
    "Almond Croissant dengan isian frangipane manis dan taburan kacang almond.",
    "Kouign-amann dengan karamelisasi gula yang sempurna di setiap lapisannya.",
    "Danish buah segar dengan custard vanilla yang lembut di bagian tengah."
  ],
  "theme": "Butter Croissant",
  "total": 5
}
###

## Get Pastry
# @name GetPastries
GET {{baseurl}}/pastries?page=1&per_page=10
Content-Type: application/json
###

## Response GetPastries
{
  "data": [
    {
      "created_at": "2026-04-11T11:35:35.327888",
      "id": 13,
      "text": "Danish buah segar dengan custard vanilla yang lembut di bagian tengah."
    },
    {
      "created_at": "2026-04-11T11:35:35.327888",
      "id": 12,
      "text": "Kouign-amann dengan karamelisasi gula yang sempurna di setiap lapisannya."
    },
    {
      "created_at": "2026-04-11T11:35:35.327888",
      "id": 11,
      "text": "Almond Croissant dengan isian frangipane manis dan taburan kacang almond."
    },
    {
      "created_at": "2026-04-11T11:35:35.327888",
      "id": 10,
      "text": "Pain au Chocolat dengan dua batang cokelat hitam premium di dalamnya."
    },
    {
      "created_at": "2026-04-11T11:35:35.327888",
      "id": 9,
      "text": "Croissant klasik dengan lapisan mentega yang renyah dan tekstur dalam yang lembut."
    },
    {
      "created_at": "2026-04-11T11:09:11.289852",
      "id": 8,
      "text": "Puff pastry hangat dengan isian daging asap dan keju yang lumer."
    },
    {
      "created_at": "2026-04-11T11:09:11.289852",
      "id": 7,
      "text": "Cinnamon Roll dengan aroma kayu manis yang kuat dan cream cheese frosting."
    },
    {
      "created_at": "2026-04-11T11:09:11.289852",
      "id": 6,
      "text": "Apple Strudel tradisional dengan potongan apel segar dan kismis manis."
    },
    {
      "created_at": "2026-04-11T11:09:11.289852",
      "id": 5,
      "text": "Palmier renyah dengan bentuk telinga gajah dan taburan gula pasir."
    },
    {
      "created_at": "2026-04-11T11:09:11.289852",
      "id": 4,
      "text": "Cronut kombinasi unik croissant dan donat dengan glaze vanilla."
    }
  ],
  "page": 1,
  "per_page": 10,
  "total": 13,
  "total_pages": 2
}
###